server:
  port: ${BACKEND_PORT:9000}
spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: "${KAFKA_SERVERS:localhost:9094}"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/identity?createDatabaseIfNotExist=true}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update

minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket: ${MINIO_BUCKET:EBook}